### PR TITLE
Add grmtools app.

### PR DESCRIPTION
**Pull request by ltratt**
grmtools (or, more specifically from this commit's perspective lrpar) is a Yacc-compatible parser written for Rust. Although it hasn't really been optimised, I thought this benchmark is sufficiently interesting that users might like to know where grmtools/lrpar fits in.

I have deliberately written the lexer and parser in not only "normal/proper Lex/Yacc style" but also "full grmtools style", including good support for error recovery, because I think that's the only mode in which grmtools makes sense. This might mean that this lexer/grammar is doing a bit more work than other parsers, but since I don't expect grmtools to be especially fast anyway, I don't suppose another few percent slowdown will hurt!

### CODE REVIEW

**Comment by epage** [comment]
> . Since every language needs a Yacc parser (there are Yacc grammars available for pretty much every language under the sun, and consequently Yacc-compatible implementations for pretty much every language),

I feel I'm missing something here.  The tokens file is universal but doesn't have much value-add.  The grammar file though is coupled to the Yacc implementation language and so it seems like "universality of yacc" is fairly limited.

**Comment by ltratt** [comment]
>The tokens file is universal but doesn't have much value-add. 

Yes, this is lrlex input (similar, but not identical, to classic Lex). Lexing is boring, which is why I didn't bother mentioning it.

>The grammar file though is coupled to the Yacc implementation language and so it seems like "universality of yacc" is fairly limited.

I'm not sure I've understood this part though? [Yacc](https://en.wikipedia.org/wiki/Yacc) is the most widely used grammar specification language; only ANTLR comes close. For example, you can take a Yacc grammar from 40+ years ago and it'll probably run through a modern Yacc system on any language (modulo the "actions", which are necessarily language specific).

**Comment by ltratt** [comment]
grmtools can, if you want, ignore the action code and produce a parse tree ([nimbleparse](https://softdevteam.github.io/grmtools/master/book/nimbleparse.html) uses this functionality) -- but that wouldn't be in the spirit of the benchmarks in this repo AFAICS, where a specific `Value` struct seems to be in keeping with the other parsers.

In practise, the "difficult" part of a `.y` file is normally seen as the grammar part: the action code is (as in the example you quote above) tends to be highly formulaic and thus "easy". In practise, this coupling of grammar + action code is what most people think of as "Yacc". It's pretty easy to take a grammar + action-code-in-another-language and change the latter to Rust (or C or ...), so Yacc files are still considered fairly portable, even if part of them is necessarily language specific.

**Comment by epage** [comment]
Thanks for the explanations.  I'll go ahead and err on the side of including it.  We can always remove it later if there is a reason to.

**Pull request merged**
